function [congruentTrls, incongruentTrls]...
    = findTrialsForCoherence(STIM,PS)
% Pull trials from STIM for use in mscohere or wcoherence

%congruentTrls
congruentTrls=  ~STIM.blank & ...
    contains(STIM.task,'brfs') &...
    STIM.tiltmatch  == 1 &...
    STIM.tilt(1)  ==  PS &...
    STIM.adapter    == 0 & ...  
    STIM.suppressor == 0 & ...
    STIM.soa        == 0 & ...
    STIM.monocular  == 0;

%incongruentTrls
incongruentTrls=  ~STIM.blank & ...
    contains(STIM.task,'brfs') &...
    STIM.tiltmatch  == 0 &...
    STIM.adapter    == 0 & ...  
    STIM.suppressor == 0 & ...
    STIM.soa        == 0 & ...
    STIM.monocular  == 0;





end