function [eyeFeatureTrls, oriFeatureTrls, tiltOfOriFeature]...
    = findTrialsForFeatures(STIM)
% Pull trials from STIM for use in RELIABILITY_SELECTION.m
% Gets out trials in a cell structure for the eye feature selection and for
% the orientation feature selection. I *think* that this will always pull
% out the two orientations primarily used on any given day. This assume
% that they are the only two orientations shown to the subject more than 15
% times. However.... this could break depending on the day, I'll have to
% find a consistant way to fix this at a later date if this is an issue.


%ipsi: eye = 2
eyeFeatureTrls{1} =  find(~STIM.blank & ...
    ~strcmp(STIM.task,'brfs') &...
    ~strcmp(STIM.task,'dbrfs') &...
    STIM.eye        == 2 &...
    STIM.adapter   == 0 & ...  
    STIM.suppressor == 0 & ...
    STIM.soa        == 0 & ...
    STIM.monocular  == 1);

%contra: eye = 3
eyeFeatureTrls{2} =  find(~STIM.blank & ...
    ~strcmp(STIM.task,'brfs') &...
    ~strcmp(STIM.task,'dbrfs') &...
    STIM.eye        == 3 &...
    STIM.adapter   == 0 & ...  
    STIM.suppressor == 0 & ...
    STIM.soa        == 0 & ...
    STIM.monocular  == 1);

uniqueTilts = nanunique(STIM.tilt(:,1));
count = 0;
clear numOriTrials oriFeature
for i = 1:size(uniqueTilts,1)
    numOriTrials(i) = sum(~STIM.blank & ...
        ~strcmp(STIM.task,'brfs') &...
        ~strcmp(STIM.task,'dbrfs') &...
        STIM.tilt(:,1)  == uniqueTilts(i) & ...
        STIM.adapter   == 0 & ...  
        STIM.suppressor == 0 & ...
        STIM.soa        == 0 & ...
        STIM.monocular  == 1);
    
    if numOriTrials(i) > 15
        count = count + 1;
        oriFeatureTrls{count} = find( ~STIM.blank & ...
        ~strcmp(STIM.task,'brfs') &...
        ~strcmp(STIM.task,'dbrfs') &...
            STIM.tilt(:,1)  == uniqueTilts(i) & ...
            STIM.adapter   == 0 & ...  
            STIM.suppressor == 0 & ...
            STIM.soa        == 0 & ...
            STIM.monocular  == 1);
        tiltOfOriFeature(count) = uniqueTilts(i);
    end
end

if size(oriFeatureTrls,2) > 2
    error('multiple monocular ori stim with high trial count - revise code')
end
% ----------------------------------->I *think* that this will always pull
% out the two orientations primarily used on any given day. This assume
% that they are the only two orientations shown to the subject more than 15
% times. However.... this could break depending on the day, I'll have to
% find a consistant way to fix this at a later date if this is an issue.








end