function       conditionarray = makeConditionArray(DE,NDE,PS,NS)
  
condition= table(...
    [DE  NDE DE  NDE DE  DE  DE  DE  DE  DE]',... %eyes1
    [PS  PS  NS  NS  PS  PS  PS  PS  PS  PS]',... %tilt1
    [1   1   1   1   1   0   1   0   1   0]',... %tiltmatch
    [0   0   0   0   0   0   1   1   1   1]',... %suppressor
    [0   0   0   0   0   0   200 200 800 800]',... %soa
    [1   1   1   1   0   0   0   0   0   0]',... %monoc
    'VariableNames',{'eyes1','tilt1','tiltmatch','suppressor','soa','monoc'});

    condition.Properties.RowNames = {...
        'Monocualr PS DE',...
        'Monocualr PS NDE',...
        'Monocualr NS DE',...
        'Monocualr NS NDE',...
        'Cong Simult',...
        'IC   Simult',...
        'Cong 200',...
        'IC   200',...
        'Cong 800',...
        'IC   800',...
        };
   
    conditionarray = table2array(condition);
    
end